# Generated by Django 5.2.14 on 2026-05-20 16:49

import django.db.models.deletion
import invoiceupgrade.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("tax_code", models.CharField(blank=True, default="", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Hóa đơn VAT"),
                            ("receipt", "Phiếu thu"),
                            ("payment", "Phiếu chi"),
                            ("warehouse", "Phiếu nhập kho"),
                        ],
                        default="invoice",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=invoiceupgrade.models.invoice_upload_path,
                        validators=[invoiceupgrade.models.validate_file_type],
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "ocr_status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ xử lý"),
                            ("processing", "Đang xử lý"),
                            ("done", "Hoàn thành"),
                            ("failed", "Thất bại"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("ocr_result", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices_upgrades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "payee_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("payee_address", models.TextField(blank=True, default="")),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "payment_method",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("cashier", models.CharField(blank=True, default="", max_length=100)),
                (
                    "accountant",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_detail",
                        to="invoiceupgrade.invoicenew",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceiptDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("receipt_date", models.DateField(blank=True, null=True)),
                (
                    "payer_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("payer_address", models.TextField(blank=True, default="")),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "payment_method",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("cashier", models.CharField(blank=True, default="", max_length=100)),
                (
                    "accountant",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt_detail",
                        to="invoiceupgrade.invoicenew",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VATInvoiceDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("invoice_date", models.DateField(blank=True, null=True)),
                (
                    "seller_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "seller_tax_code",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("seller_address", models.TextField(blank=True, default="")),
                (
                    "buyer_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "buyer_tax_code",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("buyer_address", models.TextField(blank=True, default="")),
                (
                    "payment_method",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "total_before_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vat_detail",
                        to="invoiceupgrade.invoicenew",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WarehouseDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("warehouse_date", models.DateField(blank=True, null=True)),
                (
                    "warehouse_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "supplier_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("supplier_address", models.TextField(blank=True, default="")),
                (
                    "delivery_person",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "total_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "warehouse_keeper",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "accountant",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_detail",
                        to="invoiceupgrade.invoicenew",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WarehouseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(blank=True, default="", max_length=255)),
                ("unit", models.CharField(blank=True, default="", max_length=50)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "warehouse_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="invoiceupgrade.warehousedetail",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
