# Generated by Django 5.2.14 on 2026-05-20 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoiceupgrade", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ["name"], "verbose_name_plural": "Companies"},
        ),
        migrations.AddField(
            model_name="invoicenew",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices_upgrades",
                to="invoiceupgrade.company",
            ),
        ),
    ]
