# Generated by Django 5.2.14 on 2026-05-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoiceupgrade", "0003_vatinvoiceitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vatinvoicedetail",
            old_name="total_before_tax",
            new_name="change_amount",
        ),
        migrations.RemoveField(
            model_name="vatinvoicedetail",
            name="buyer_address",
        ),
        migrations.RemoveField(
            model_name="vatinvoicedetail",
            name="buyer_name",
        ),
        migrations.RemoveField(
            model_name="vatinvoicedetail",
            name="buyer_tax_code",
        ),
        migrations.RemoveField(
            model_name="vatinvoicedetail",
            name="invoice_code",
        ),
        migrations.RemoveField(
            model_name="vatinvoicedetail",
            name="seller_address",
        ),
        migrations.RemoveField(
            model_name="vatinvoicedetail",
            name="seller_tax_code",
        ),
        migrations.RemoveField(
            model_name="vatinvoicedetail",
            name="tax_rate",
        ),
        migrations.AddField(
            model_name="vatinvoicedetail",
            name="received_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="vatinvoicedetail",
            name="subtotal",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="vatinvoicedetail",
            name="total_discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
