# Generated by Django 5.2.14 on 2026-05-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "invoiceupgrade",
            "0004_rename_total_before_tax_vatinvoicedetail_change_amount_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicenew",
            name="source",
            field=models.CharField(
                choices=[("manual", "Nhập thủ công"), ("ai", "Import AI")],
                default="manual",
                max_length=10,
            ),
        ),
    ]
