# Generated by Django 5.2.14 on 2026-05-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoiceupgrade", "0005_invoicenew_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicenew",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Nhập thủ công"),
                    ("ai", "Import AI"),
                    ("gemini", "Google Gemini"),
                ],
                default="manual",
                max_length=10,
            ),
        ),
    ]
